### ISSUE TITLE
Video candidate

### ISSUE THREAD

**Issue by davelab6** [notofonts/noto-docs#6]
https://vimeo.com/435930677

"How to Kill a Writing System with Zachary Scheuren"

Monday, July 6, 2020

Letterform Archive

> Writing systems live and breathe with the people who use them, but sometimes they can become difficult or impossible to use. In many cases a writing system has been deliberately pushed out of use or even out of existence. What does it take to kill a writing system? What does it take to bring one back to life? In the current digital world if a writing system is implemented in computing systems it can be immediately seen and used by billions of people around the world. However, if there is no support users must resort to other means. But why should they compromise?
>
> www.letterformarchive.org/events/how-to-kill-a-writing-system

**Comment by twardoch** [comment]
Added to https://github.com/notofonts/noto-docs/blob/main/docs/general/videos.md
